### ISSUE TITLE
add option to keep all pmids to post_process.py

### ISSUE THREAD

**Issue by santogiovanni** [TheJacksonLaboratory/marea#55]
In the oriignal marea, we focused on cancer-relevant abstracts. For the new project, we want to keep all abstracts.
This line in post_process.py needs to be adjusted
```
(l.59) if pmid in relevant:
```

We could add a command line parameter ``--keep-all`` and change the above line to
```
(l.59) if keep_all or pmid in relevant:
```

**Comment by hannahblau** [comment]
This issue is addressed with bypass_filter.sh in the bash_scripts folder of the marea project. bypass_filter.sh treats every PubMed abstract as relevant and copies its information for further processing.
